apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::743175288773:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-145JT9BAVKFO3
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::743175288773:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
    
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-15T05:51:51Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "910"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c2d1541b-ff9e-427f-bae0-ef993c5c9c38
